spring.application.name=${SPRING_APPLICATION_NAME}

server.port=${SERVER_PORT}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL-AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

# GraphQL
spring.graphql.graphiql.enabled=${SPRING_GRAPHQL_GRAPHIQL_ENABLED}

#Security
application.security.jwt.secret-key=${JWT_SECRET}
